# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
    }:
    runCommand "${name}.tar.gz"
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "flat";
      }
      ''
        touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
      '';
in
linkFarm name [
  {
    name = "sdfgen-0.0.0-kupG3yryBwDhOJWuex-WQ-VfCr5l_4EdVYYXqItOype_.tar.gz";
    path = fetchZig {
      name = "sdfgen";
      url = "https://github.com/au-ts/microkit_sdf_gen/archive/13686a373b9189c7b1d778cd749d7d8bbd8a63f6.tar.gz";
      hash = "sha256-YjjdWCG46KolFCB2sVlXKzJP5j/9+6/wJZMw5eDwiWY=";
    };
  }
  {
    name = "dtb-0.0.0-gULdmT8JAgAO49xxrRGA_0_0v4nPL7D91Ev2x7NnNbmy.tar.gz";
    path = fetchZig {
      name = "dtb";
      url = "https://github.com/Ivan-Velickovic/dtb.zig/archive/13d4cc60806f4655043d00df50d4225737b268d4.tar.gz";
      hash = "sha256-lL2sAXw2kE+J3uupbBeUHqQji7r328lTpU4zP9wKyzM=";
    };
  }
  {
    name = "sddf-0.0.0-6aJ67hfnZgCIb73S-PWM-oHDp0RadrbTQqB2Cc7wDlln.tar.gz";
    path = fetchZig {
      name = "sddf";
      url = "https://github.com/au-ts/sddf/archive/e8341acea643c818e59033812accdc531fb82201.tar.gz";
      hash = "sha256-xdtYd/O9dQNwg71O9uHb567aT+5f7PD34IFE9ejIp+c=";
    };
  }
]
