/*
 * In-memory filesystem for Chrysopolis (Option C workaround).
 *
 * Provides ERTS with boot script and OTP modules embedded in the image.
 * Files are served from a static table instead of requiring disk I/O.
 */
#include <lions/posix/fd.h>
#include <lions/posix/posix.h>

#include <microkit.h>

#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>

/* File table generated by gen-boot-data.sh and linked from boot_data.o */
typedef struct {
  const char *path;
  const unsigned char *data;
  size_t size;
} memfs_file_t;

extern const memfs_file_t boot_files[];

/* Forward declarations */
int memfs_stat(const char *path, struct stat *st);

/* Per-fd state for open files */
typedef struct {
  const memfs_file_t *file;
  size_t offset;
} memfs_state_t;

static memfs_state_t memfs_states[32]; /* Matches fd limit */

const memfs_file_t *memfs_lookup(const char *path) {
  if (path == NULL) {
    return NULL;
  }

  /* Normalize path by skipping extra leading slashes (// -> /) */
  while (path[0] == '/' && path[1] == '/') {
    path++;
  }

  for (const memfs_file_t *f = boot_files; f->path != NULL; f++) {
    if (strcmp(f->path, path) == 0) {
      return f;
    }
  }
  return NULL;
}

/* Read from in-memory file */
ssize_t memfs_read(void *buf, size_t count, int fd) {
  if (fd < 0 || fd >= 32) {
    return -EBADF;
  }

  memfs_state_t *state = &memfs_states[fd];
  if (state->file == NULL) {
    return -EBADF;
  }

  /* Handle device files */
  if (strcmp(state->file->path, "/dev/null") == 0) {
    return 0; /* EOF */
  }
  if (strcmp(state->file->path, "/dev/zero") == 0) {
    memset(buf, 0, count);
    return count;
  }
  if (strcmp(state->file->path, "/dev/urandom") == 0) {
    /* Poor man's randomness - enough for ERTS init */
    for (size_t i = 0; i < count; i++) {
      ((unsigned char *)buf)[i] = (unsigned char)(i ^ (state->offset + i));
    }
    state->offset += count;
    return count;
  }

  /* Regular file */
  if (state->file->data == NULL || state->file->size == 0) {
    return 0; /* Empty file */
  }

  size_t remaining = state->file->size - state->offset;
  if (remaining == 0) {
    return 0; /* EOF */
  }

  size_t to_read = (count < remaining) ? count : remaining;
  memcpy(buf, state->file->data + state->offset, to_read);
  state->offset += to_read;

  return to_read;
}

/* Write to in-memory file (discard for device files) */
ssize_t memfs_write(const void *buf, size_t count, int fd) {
  (void)buf;
  if (fd < 0 || fd >= 32) {
    return -EBADF;
  }

  memfs_state_t *state = &memfs_states[fd];
  if (state->file == NULL) {
    return -EBADF;
  }

  /* Device files accept writes (discard) */
  if (strncmp(state->file->path, "/dev/", 5) == 0) {
    return count;
  }

  /* Regular files are read-only */
  return -EROFS;
}

/* Close in-memory file */
int memfs_close(int fd) {
  if (fd < 0 || fd >= 32) {
    return -EBADF;
  }

  memfs_states[fd].file = NULL;
  memfs_states[fd].offset = 0;
  return posix_fd_deallocate(fd);
}

/* Fstat in-memory file (for fd-based fstat) */
int memfs_fstat(int fd, struct stat *st) {
  if (fd < 0 || fd >= 32) {
    return -EBADF;
  }

  memfs_state_t *state = &memfs_states[fd];
  if (state->file == NULL) {
    return -EBADF;
  }

  return memfs_stat(state->file->path, st);
}

/* Open in-memory file */
int memfs_open(const char *path, int flags) {
  /* Normalize path by skipping extra leading slashes (// -> /) */
  while (path[0] == '/' && path[1] == '/') {
    path++;
  }

  const memfs_file_t *file = memfs_lookup(path);
  if (file == NULL) {
    return -ENOENT;
  }

  int fd = posix_fd_allocate();
  if (fd < 0) {
    return -EMFILE;
  }

  fd_entry_t *e = posix_fd_entry(fd);
  if (e == NULL) {
    return -EMFILE;
  }

  e->read = memfs_read;
  e->write = memfs_write;
  e->close = memfs_close;
  e->fstat = memfs_fstat;
  e->dup3 = NULL; /* Not supported */
  e->flags = flags;
  e->file_ptr = 0;

  memfs_states[fd].file = file;
  memfs_states[fd].offset = 0;

  return fd;
}

/* Stat in-memory file */
int memfs_stat(const char *path, struct stat *st) {
  const memfs_file_t *file = memfs_lookup(path);
  if (file == NULL) {
    return -ENOENT;
  }

  if (st != NULL) {
    memset(st, 0, sizeof(*st));

    /* Device files */
    if (strncmp(file->path, "/dev/", 5) == 0) {
      st->st_mode = S_IFCHR | 0666;
      st->st_rdev = 0;
      st->st_size = 0;
    } else {
      /* Regular file */
      st->st_mode = S_IFREG | 0444;
      st->st_size = file->size;
    }

    st->st_nlink = 1;
    st->st_blksize = 4096;
    st->st_blocks = (st->st_size + 511) / 512;
  }

  return 0;
}

void memfs_init(void) { memset(memfs_states, 0, sizeof(memfs_states)); }
