# Generated by rebar3_nix
let
  fetchOnly = { src, ... }: src;
in
{
  builder ? fetchOnly,
  fetchHex,
  fetchgit,
  fetchFromGitHub,
  overrides ? (x: y: { }),
}:
let
  self = packages // (overrides self packages);
  packages = with self; {
    proper = builder {
      name = "proper";
      version = "1.5.0";
      src = fetchHex {
        pkg = "proper";
        version = "1.5.0";
        sha256 = "sha256-+/fPBiXlRBoxRRT32OHq/1IJD82U/zS1Fx/yk9P5lpo=";
      };
      beamDeps = [ ];
    };
  };
in
self
