//! C23 headers for the orchestration ABI, emitted into a build directory and never committed.
//! Layout asserts come from the extern structs; checkers from checks.zig. Output includes only
//! <stdint.h> <stddef.h> <stdbool.h> <stdatomic.h> and reads bytes without casting to records.
const std = @import("std");
const system = @import("system_abi");
const abi = @import("orchestrator_abi");
const model = @import("model");
const checks = @import("checks");

const Writer = std.Io.Writer;

pub const Header = struct {
    name: []const u8,
    guard: []const u8,
    summary: []const u8,
    records: []const []const u8 = &.{},
    checkers: []const []const u8 = &.{},
    kind: enum { common, records, system } = .records,
    status_copy: bool = false,
};

pub const headers = [_]Header{
    .{
        .name = "orchestrator_abi.h",
        .guard = "CHRYSOPOLIS_ORCHESTRATOR_ABI_H",
        .summary = "Orchestration ABI version, wire magics, enums, the slot transition\n * table, and the byte helpers every generated checker uses.",
        .kind = .common,
    },
    .{
        .name = "root_control.h",
        .guard = "CHRYSOPOLIS_ROOT_CONTROL_H",
        .summary = "Root control plane records: the status page, the double-banked spec page\n * and the control command and reply.",
        .records = &.{ "RootStatusHeader", "RootChildStatus", "RootEvent", "RootStatusPage", "SpecHeader", "SpecBank", "SpecPage", "CtlCommand", "CtlReply" },
        .checkers = &.{ "root_status_page", "spec_header", "spec_bank", "ctl_command", "ctl_reply" },
        .status_copy = true,
    },
    .{
        .name = "worker_identity.h",
        .guard = "CHRYSOPOLIS_WORKER_IDENTITY_H",
        .summary = "Worker identity page, written by BEAM and read by one worker.",
        .records = &.{ "WorkerIdentityHeader", "WorkerIdentity" },
        .checkers = &.{"worker_identity"},
    },
    .{
        .name = "worker_status.h",
        .guard = "CHRYSOPOLIS_WORKER_STATUS_H",
        .summary = "Worker status page, written by one worker and read by BEAM.",
        .records = &.{ "WorkerStatusHeader", "WorkerStatus" },
        .checkers = &.{"worker_status"},
    },
    .{
        .name = "worker_protocol.h",
        .guard = "CHRYSOPOLIS_WORKER_PROTOCOL_H",
        .summary = "Request and completion journals between BEAM and one worker.",
        .records = &.{ "JournalHeader", "JournalEntry", "JournalPage" },
        .checkers = &.{ "request_journal", "completion_journal" },
    },
    .{
        .name = "system_abi.h",
        .guard = "CHRYSOPOLIS_SYSTEM_ABI_H",
        .summary = "Control plane and worker pool topology from the typed system ABI.\n * runtime_abi.h keeps the pre-orchestration constants; nothing here repeats them.",
        .kind = .system,
    },
};

comptime {
    // Build scripts read the header list from headers.zig; keep the two identical.
    const names = @import("headers.zig").names;
    if (names.len != headers.len) @compileError("headers.zig and generate_c.headers differ");
    for (names, headers) |name, header| {
        if (!std.mem.eql(u8, name, header.name)) @compileError("headers.zig and generate_c.headers differ");
    }
}

const snake = @import("naming").snake;

fn scalarType(width: usize) []const u8 {
    return switch (width) {
        1 => "uint8_t",
        2 => "uint16_t",
        4 => "uint32_t",
        8 => "uint64_t",
        else => unreachable,
    };
}

/// Width of one scalar element; model.zig admits only u8, u16, u32 and u64.
fn elementWidth(field: model.Field) usize {
    return field.size / field.count;
}

fn loader(width: usize) []const u8 {
    return switch (width) {
        1 => "chryso_abi_load_u8",
        2 => "chryso_abi_load_u16le",
        4 => "chryso_abi_load_u32le",
        8 => "chryso_abi_load_u64le",
        else => unreachable,
    };
}

fn isAtomic(record: []const u8, field: []const u8) bool {
    for (abi.atomic_fields) |atomic| {
        if (std.mem.eql(u8, atomic.record, record) and std.mem.eql(u8, atomic.field, field)) return true;
    }
    return false;
}

fn classConstant(class: checks.Class) []const u8 {
    return switch (class) {
        inline else => |tag| "chryso_abi_reject_" ++ @tagName(tag),
    };
}

fn writePreamble(w: *Writer, header: Header) Writer.Error!void {
    try w.print(
        \\/* Generated by tools/abi from interfaces/orchestrator_abi.zig and
        \\ * interfaces/system_abi.zig. Do not edit and do not commit.
        \\ *
        \\ * {s}
        \\ */
        \\#ifndef {s}
        \\#define {s} 1
        \\
        \\#include <stdbool.h>
        \\#include <stddef.h>
        \\#include <stdint.h>
        \\
    , .{ header.summary, header.guard, header.guard });
    switch (header.kind) {
        .common => try w.writeAll("#include <stdatomic.h>\n"),
        .records => try w.writeAll("#include <stdatomic.h>\n\n#include <chrysopolis/orchestrator_abi.h>\n"),
        .system => {},
    }
    try w.writeByte('\n');
}

fn writeLiteral(w: *Writer, value: u64, width: usize) Writer.Error!void {
    if (width == 8) try w.print("UINT64_C({d})", .{value}) else try w.print("{d}u", .{value});
}

fn writeCommon(w: *Writer) Writer.Error!void {
    const d = model.description;
    try w.print("static constexpr uint32_t chryso_abi_version = {d}u;\n", .{d.abi_version});
    try w.writeAll("/* CRC-32 of the whole wire contract; peers must agree before exchanging records. */\n");
    try w.print("static constexpr uint32_t chryso_abi_layout_digest = 0x{x:0>8}u;\n", .{model.layoutDigest(d)});
    try w.print("static constexpr size_t chryso_child_count = {d}u;\n", .{d.constants.child_count});
    try w.print("static constexpr size_t chryso_event_count = {d}u;\n", .{d.constants.event_count});
    try w.print("static constexpr size_t chryso_journal_capacity = {d}u;\n", .{d.constants.journal_capacity});
    try w.print("static constexpr size_t chryso_journal_payload_size = {d}u;\n", .{d.constants.journal_payload_size});
    try w.print("static constexpr uint8_t chryso_root_event_no_child = {d}u;\n", .{d.constants.root_event_no_child});
    try w.print("static constexpr uint16_t chryso_fault_mr0_valid = {d}u;\n", .{d.constants.fault_mr0_valid});
    try w.print("static constexpr uint16_t chryso_fault_mr1_valid = {d}u;\n", .{d.constants.fault_mr1_valid});
    try w.print("static constexpr uint16_t chryso_down_interval_open = {d}u;\n\n", .{d.constants.down_interval_open});

    try w.writeAll("/* Wire magics: little-endian u64 values whose memory bytes spell the ASCII. */\n");
    for (d.magics) |magic| {
        try w.print("static constexpr uint64_t chryso_magic_{s} = UINT64_C(0x{x:0>16}); /* \"{s}\" */\n", .{ magic.name, magic.value, magic.bytes });
    }
    try w.writeByte('\n');

    for (d.enums) |enumeration| {
        if (!enumeration.wire and !std.mem.eql(u8, enumeration.name, "AbiReject") and
            !std.mem.eql(u8, enumeration.name, "SlotEvent")) continue;
        if (std.mem.eql(u8, enumeration.name, "AbiReject"))
            try w.writeAll("/* A decoder verdict, never a byte in a wire record. */\n")
        else if (!enumeration.wire)
            try w.writeAll("/* Transition labels; not carried in any wire record. */\n");
        try w.print("typedef enum chryso_{f} : {s} {{\n", .{ snake(enumeration.name), scalarType(enumeration.width) });
        for (enumeration.values) |value| {
            // Hex keeps sparse tags such as 0x8001 recognisable.
            if (value.value > 255)
                try w.print("  chryso_{f}_{s} = 0x{x}u,\n", .{ snake(enumeration.name), value.name, value.value })
            else
                try w.print("  chryso_{f}_{s} = {d}u,\n", .{ snake(enumeration.name), value.name, value.value });
        }
        try w.print("}} chryso_{f};\n\n", .{snake(enumeration.name)});
        if (!enumeration.wire) continue;
        try w.print(
            \\/* True when value is a declared {s}, including a zero tag. */
            \\[[__nodiscard__]] static inline bool chryso_{f}_is_member({s} value) {{
            \\  switch (value) {{
            \\
        , .{ enumeration.name, snake(enumeration.name), scalarType(enumeration.width) });
        for (enumeration.values) |value| {
            try w.print("  case chryso_{f}_{s}:\n", .{ snake(enumeration.name), value.name });
        }
        try w.writeAll(
            \\    return true;
            \\  default:
            \\    return false;
            \\  }
            \\}
            \\
            \\
        );
    }

    try w.print(
        \\typedef struct chryso_slot_transition {{
        \\  chryso_slot_phase from;
        \\  chryso_slot_phase to;
        \\  chryso_slot_event event;
        \\}} chryso_slot_transition;
        \\
        \\/* Every legal slot lifecycle edge; (from, event) is unique. */
        \\static const chryso_slot_transition chryso_slot_transitions[{d}] = {{
        \\
    , .{d.transitions.len});
    for (d.transitions) |transition| {
        try w.print("    {{.from = chryso_slot_phase_{s}, .to = chryso_slot_phase_{s}, .event = chryso_slot_event_{s}}},\n", .{ transition.from, transition.to, transition.event });
    }
    try w.writeAll(
        \\};
        \\
        \\/* Hot _Atomic fields must be lock-free on every target. */
        \\static_assert(ATOMIC_INT_LOCK_FREE == 2);
        \\static_assert(ATOMIC_LONG_LOCK_FREE == 2);
        \\static_assert(ATOMIC_LLONG_LOCK_FREE == 2);
        \\
        \\/* Little-endian loads from any alignment. */
        \\[[__nodiscard__]] static inline uint8_t chryso_abi_load_u8(const uint8_t *bytes) {
        \\  return bytes[0];
        \\}
        \\
        \\[[__nodiscard__]] static inline uint16_t chryso_abi_load_u16le(const uint8_t *bytes) {
        \\  return (uint16_t)((uint32_t)bytes[0] | ((uint32_t)bytes[1] << 8));
        \\}
        \\
        \\[[__nodiscard__]] static inline uint32_t chryso_abi_load_u32le(const uint8_t *bytes) {
        \\  return (uint32_t)bytes[0] | ((uint32_t)bytes[1] << 8) |
        \\         ((uint32_t)bytes[2] << 16) | ((uint32_t)bytes[3] << 24);
        \\}
        \\
        \\[[__nodiscard__]] static inline uint64_t chryso_abi_load_u64le(const uint8_t *bytes) {
        \\  return (uint64_t)chryso_abi_load_u32le(bytes) |
        \\         ((uint64_t)chryso_abi_load_u32le(bytes + 4) << 32);
        \\}
        \\
        \\[[__nodiscard__]] static inline bool chryso_abi_all_zero(const uint8_t *bytes,
        \\                                                        size_t count) {
        \\  unsigned int seen = 0;
        \\  for (size_t i = 0; i < count; i++) {
        \\    seen |= (unsigned int)bytes[i];
        \\  }
        \\  return seen == 0u;
        \\}
        \\
        \\/* CRC-32/IEEE, table-free. Seed 0xFFFFFFFF and complement the result. */
        \\[[__nodiscard__]] static inline uint32_t
        \\chryso_abi_crc32_update(uint32_t crc, const uint8_t *bytes, size_t count) {
        \\  for (size_t i = 0; i < count; i++) {
        \\    crc ^= (uint32_t)bytes[i];
        \\    for (unsigned int bit = 0; bit < 8u; bit++) {
        \\      crc = (crc >> 1) ^ (UINT32_C(0xEDB88320) & (0u - (crc & 1u)));
        \\    }
        \\  }
        \\  return crc;
        \\}
        \\
        \\/* Feed count zero bytes for fields the checksum reads as zero. */
        \\[[__nodiscard__]] static inline uint32_t chryso_abi_crc32_zeros(uint32_t crc,
        \\                                                               size_t count) {
        \\  for (size_t i = 0; i < count; i++) {
        \\    for (unsigned int bit = 0; bit < 8u; bit++) {
        \\      crc = (crc >> 1) ^ (UINT32_C(0xEDB88320) & (0u - (crc & 1u)));
        \\    }
        \\  }
        \\  return crc;
        \\}
        \\
        \\[[__nodiscard__]] static inline uint32_t chryso_abi_crc32_final(uint32_t crc) {
        \\  return crc ^ UINT32_C(0xFFFFFFFF);
        \\}
        \\
        \\[[__nodiscard__]] static inline uint32_t chryso_abi_crc32(const uint8_t *bytes,
        \\                                                         size_t count) {
        \\  return chryso_abi_crc32_final(
        \\      chryso_abi_crc32_update(UINT32_C(0xFFFFFFFF), bytes, count));
        \\}
        \\
        \\
    );
}

fn writeRecord(w: *Writer, record: model.Record) Writer.Error!void {
    try w.print("/* {s}: {d} bytes. */\ntypedef struct chryso_{f} {{\n", .{ record.name, record.size, snake(record.name) });
    for (record.fields) |field| {
        if (field.is_record) {
            try w.print("  chryso_{f} {s}", .{ snake(field.element), field.name });
        } else if (isAtomic(record.name, field.name)) {
            try w.print("  _Atomic({s}) {s}", .{ scalarType(elementWidth(field)), field.name });
        } else {
            try w.print("  {s} {s}", .{ scalarType(elementWidth(field)), field.name });
        }
        if (field.count != 1) try w.print("[{d}]", .{field.count});
        try w.writeAll(";\n");
    }
    try w.print("}} chryso_{f};\n", .{snake(record.name)});
    try w.print("static_assert(sizeof(chryso_{f}) == {d});\n", .{ snake(record.name), record.size });
    try w.print("static_assert(alignof(chryso_{f}) == {d});\n", .{ snake(record.name), record.alignment });
    for (record.fields) |field| {
        try w.print("static_assert(offsetof(chryso_{f}, {s}) == {d});\n", .{ snake(record.name), field.name, field.offset });
    }
    try w.writeByte('\n');
}

/// One rule's test against the scope instance at `at`.
fn writeCheck(w: *Writer, check: checks.Check, at: []const u8, class: checks.Class, indent: []const u8) Writer.Error!void {
    const ret = classConstant(class);
    switch (check) {
        .magic => |value| {
            const name = magicName(value.value);
            try w.print("{s}if (chryso_abi_load_u64le({s} + {d}u) != chryso_magic_{s}) {{\n{s}  return {s};\n{s}}}\n", .{ indent, at, value.int.offset, name, indent, ret, indent });
        },
        .version => |value| {
            std.debug.assert(value.value == abi.abi_version);
            try w.print("{s}if ((uint32_t){s}({s} + {d}u) != chryso_abi_version) {{\n{s}  return {s};\n{s}}}\n", .{ indent, loader(value.int.width), at, value.int.offset, indent, ret, indent });
        },
        .equal => |value| {
            try w.print("{s}if ((uint64_t){s}({s} + {d}u) != ", .{ indent, loader(value.int.width), at, value.int.offset });
            try writeLiteral(w, value.value, 8);
            try w.print(") {{\n{s}  return {s};\n{s}}}\n", .{ indent, ret, indent });
        },
        .at_most => |value| {
            try w.print("{s}if ((uint64_t){s}({s} + {d}u) > ", .{ indent, loader(value.int.width), at, value.int.offset });
            try writeLiteral(w, value.value, 8);
            try w.print(") {{\n{s}  return {s};\n{s}}}\n", .{ indent, ret, indent });
        },
        .ring_dropped => |value| try w.print(
            "{s}{{\n{s}  const uint64_t head = chryso_abi_load_u64le({s} + {d}u);\n{s}  const uint64_t dropped = chryso_abi_load_u64le({s} + {d}u);\n{s}  if (dropped != (head > {d}u ? head - {d}u : 0u)) {{\n{s}    return {s};\n{s}  }}\n{s}}}\n",
            .{ indent, indent, at, value.head.offset, indent, at, value.dropped.offset, indent, value.capacity, value.capacity, indent, ret, indent, indent },
        ),
        .event_child => |value| {
            try w.print("{s}{{\n{s}  const uint8_t kind = chryso_abi_load_u8({s} + {d}u);\n{s}  const uint8_t child = chryso_abi_load_u8({s} + {d}u);\n{s}  if (", .{
                indent, indent, at, value.kind.offset, indent, at, value.child.offset, indent,
            });
            try writeKindSet(w, value.global);
            try w.print(" ? child != {d}u : (child >= {d}u || chryso_abi_load_u8(bytes + {d}u + (size_t)child * {d}u + {d}u) == 0u)) {{\n{s}    return {s};\n{s}  }}\n{s}}}\n", .{
                value.sentinel, value.targets.count, value.targets.base, value.targets.stride, value.target_state.offset,
                indent,         ret,                 indent,             indent,
            });
        },
        .only_for_kind => |value| try w.print(
            "{s}if ((uint64_t){s}({s} + {d}u) != 0u && (uint64_t){s}({s} + {d}u) != {d}u) {{\n{s}  return {s};\n{s}}}\n",
            .{ indent, loader(value.int.width), at, value.int.offset, loader(value.kind.width), at, value.kind.offset, value.value, indent, ret, indent },
        ),
        .implies => |value| try w.print(
            "{s}{{\n{s}  const uint64_t raw = (uint64_t){s}({s} + {d}u);\n{s}  if ((raw & {d}u) != 0u && (raw & {d}u) != {d}u) {{\n{s}    return {s};\n{s}  }}\n{s}}}\n",
            .{ indent, indent, loader(value.int.width), at, value.int.offset, indent, value.when, value.requires, value.requires, indent, ret, indent, indent },
        ),
        .zero_when_unset => |value| try w.print(
            "{s}if ((uint64_t){s}({s} + {d}u) == 0u && !chryso_abi_all_zero({s} + {d}u, {d}u)) {{\n{s}  return {s};\n{s}}}\n",
            .{ indent, loader(value.int.width), at, value.int.offset, at, value.span.offset, value.span.len, indent, ret, indent },
        ),
        .kind_member => |value| {
            const member = value.member;
            try w.print("{s}if ((uint64_t){s}({s} + {d}u) == {d}u) {{\n{s}  const {s} value = {s}({s} + {d}u);\n{s}  if (", .{
                indent, loader(value.kind.width),     at,                       value.kind.offset, value.value,
                indent, scalarType(member.int.width), loader(member.int.width), at,                member.int.offset,
                indent,
            });
            if (member.reject_zero) try w.writeAll("value == 0u || ");
            try w.print("!chryso_{f}_is_member(value)) {{\n{s}    return {s};\n{s}  }}\n{s}}}\n", .{ snake(member.enumeration), indent, ret, indent, indent });
        },
        .seqlock => |value| try w.print(
            \\{s}{{
            \\{s}  const uint64_t seq = (uint64_t){s}({s} + {d}u);
            \\{s}  if (seq == 0u || (seq & 1u) != 0u) {{
            \\{s}    return {s};
            \\{s}  }}
            \\{s}}}
            \\
        , .{ indent, indent, loader(value.width), at, value.offset, indent, indent, ret, indent, indent }),
        .nonzero => |value| try w.print(
            \\{s}if ((uint64_t){s}({s} + {d}u) == 0u) {{
            \\{s}  return {s};
            \\{s}}}
            \\
        , .{ indent, loader(value.width), at, value.offset, indent, ret, indent }),
        .zero => |value| try w.print(
            \\{s}if (!chryso_abi_all_zero({s} + {d}u, {d}u)) {{
            \\{s}  return {s};
            \\{s}}}
            \\
        , .{ indent, at, value.offset, value.len, indent, ret, indent }),
        .member => |value| {
            try w.print("{s}{{\n{s}  const {s} value = {s}({s} + {d}u);\n{s}  if (", .{
                indent, indent,           scalarType(value.int.width), loader(value.int.width),
                at,     value.int.offset, indent,
            });
            if (value.reject_zero) try w.writeAll("value == 0u || ");
            try w.print("!chryso_{f}_is_member(value)) {{\n{s}    return {s};\n{s}  }}\n{s}}}\n", .{ snake(value.enumeration), indent, ret, indent, indent });
        },
        .crc32 => |value| {
            try w.print("{s}{{\n{s}  uint32_t crc = UINT32_C(0xFFFFFFFF);\n", .{ indent, indent });
            var cursor = value.span.offset;
            const zero_spans = [_]checks.Span{.{ .offset = value.crc.offset, .len = value.crc.width }};
            for (&[_][]const checks.Span{ &zero_spans, value.zeroed }) |group| {
                for (group) |zeroed| {
                    if (zeroed.offset > cursor)
                        try w.print("{s}  crc = chryso_abi_crc32_update(crc, {s} + {d}u, {d}u);\n", .{ indent, at, cursor, zeroed.offset - cursor });
                    try w.print("{s}  crc = chryso_abi_crc32_zeros(crc, {d}u);\n", .{ indent, zeroed.len });
                    cursor = zeroed.offset + zeroed.len;
                }
            }
            const end = value.span.offset + value.span.len;
            if (end > cursor)
                try w.print("{s}  crc = chryso_abi_crc32_update(crc, {s} + {d}u, {d}u);\n", .{ indent, at, cursor, end - cursor });
            try w.print(
                \\{s}  if (chryso_abi_crc32_final(crc) != chryso_abi_load_u32le({s} + {d}u)) {{
                \\{s}    return {s};
                \\{s}  }}
                \\{s}}}
                \\
            , .{ indent, at, value.crc.offset, indent, ret, indent, indent });
        },
        .entry_identity => |value| try w.print(
            \\{s}if (chryso_abi_load_u64le({s} + {d}u) != chryso_abi_load_u64le(bytes + {d}u) ||
            \\{s}    chryso_abi_load_u64le({s} + {d}u) != sequence) {{
            \\{s}  return {s};
            \\{s}}}
            \\
        , .{ indent, at, value.generation.offset, value.header_generation, indent, at, value.sequence.offset, indent, ret, indent }),
        .payload_tail => |value| try w.print(
            \\{s}{{
            \\{s}  const size_t used = (size_t){s}({s} + {d}u);
            \\{s}  const size_t kept = used < {d}u ? used : {d}u;
            \\{s}  if (!chryso_abi_all_zero({s} + {d}u + kept, {d}u - kept)) {{
            \\{s}    return {s};
            \\{s}  }}
            \\{s}}}
            \\
        , .{
            indent, indent, loader(value.length.width), at,                value.length.offset, indent, value.payload.len, value.payload.len,
            indent, at,     value.payload.offset,       value.payload.len, indent,              ret,    indent,            indent,
        }),
    }
}

/// `(kind == a || kind == b)`, or `false` for an empty set.
fn writeKindSet(w: *Writer, kinds: []const u64) Writer.Error!void {
    if (kinds.len == 0) return w.writeAll("false");
    try w.writeByte('(');
    for (kinds, 0..) |kind, i| {
        if (i != 0) try w.writeAll(" || ");
        try w.print("kind == {d}u", .{kind});
    }
    try w.writeByte(')');
}

fn magicName(value: u64) []const u8 {
    for (model.description.magics) |magic| {
        if (magic.value == value) return magic.name;
    }
    unreachable; // validateChecks ties rule magics to declared magics
}

/// Consecutive rules with one class and scope share a loop; the verdict only depends on the class.
fn writeRules(w: *Writer, group: []const checks.Rule) Writer.Error!void {
    const rule = group[0];
    switch (rule.scope) {
        .whole => for (group) |item| try writeCheck(w, item.check, "bytes", item.class, "  "),
        .selected => for (group) |item| try writeCheck(w, item.check, "selected", item.class, "  "),
        .rows => |rows| {
            try w.print(
                \\  for (size_t row = 0; row < {d}u; row++) {{
                \\    const uint8_t *const at = bytes + {d}u + row * {d}u;
                \\
            , .{ rows.count, rows.base, rows.stride });
            for (group) |item| try writeCheck(w, item.check, "at", item.class, "    ");
            try w.writeAll("  }\n");
        },
        .window => |window| {
            try w.print(
                \\  {{
                \\    const uint64_t head = chryso_abi_load_u64le(bytes + {d}u);
                \\    const uint64_t live = head < {d}u ? head : {d}u;
                \\    for (uint64_t n = 0; n < live; n++) {{
                \\
            , .{ window.head_offset, window.capacity, window.capacity });
            switch (window.mode) {
                .ring => try w.print(
                    \\      const uint64_t index = head - live + n;
                    \\      const uint8_t *const at = bytes + {d}u + (size_t)(index % {d}u) * {d}u;
                    \\
                , .{ window.base, window.capacity, window.stride }),
                .journal => try w.print(
                    \\      const uint64_t sequence = head - live + n + 1u;
                    \\      const uint8_t *const at = bytes + {d}u + (size_t)((sequence - 1u) % {d}u) * {d}u;
                    \\
                , .{ window.base, window.capacity, window.stride }),
            }
            for (group) |item| try writeCheck(w, item.check, "at", item.class, "      ");
            try w.writeAll("    }\n  }\n");
        },
    }
}

fn writeChecker(w: *Writer, checker: checks.Checker) Writer.Error!void {
    try w.print(
        \\/* Checks one {s} snapshot of {d} bytes at any alignment and returns the
        \\ * highest-precedence violation or chryso_abi_reject_ok. Reads only; keeps no
        \\ * pointer; the bytes must not change during the call (copy shared pages first). */
        \\[[__nodiscard__]] static inline chryso_abi_reject
        \\chryso_check_{s}(const uint8_t *bytes, size_t len
    , .{ checker.record, checker.size, checker.name });
    if (checker.selector != null) try w.writeAll(", size_t bank");
    try w.print(
        \\) {{
        \\  if (bytes == nullptr || len != {d}u) {{
        \\    return chryso_abi_reject_size;
        \\  }}
        \\
    , .{checker.size});
    if (checker.selector) |selector| try w.print(
        \\  if (bank >= {d}u) {{
        \\    return chryso_abi_reject_range;
        \\  }}
        \\  const uint8_t *const selected = bytes + {d}u + bank * {d}u;
        \\
    , .{ selector.count, selector.base, selector.stride });
    var start: usize = 0;
    while (start < checker.rules.len) {
        var end = start + 1;
        while (end < checker.rules.len and checker.rules[end].class == checker.rules[start].class and
            std.meta.eql(checker.rules[end].scope, checker.rules[start].scope)) end += 1;
        try writeRules(w, checker.rules[start..end]);
        start = end;
    }
    try w.writeAll("  return chryso_abi_reject_ok;\n}\n\n");
}

const status_copy =
    \\/* Seqlock ordering, single writer, unicore or restart only.
    \\ * Writer: odd seq, release fence, payload, release-store next even seq.
    \\ * Reader: acquire-load seq, copy, acquire fence, relaxed reload. The fence
    \\ * stops the copy sinking below the reload. SMP readers still need atomic
    \\ * payload access. Accept a copy only when both loads are equal, even, nonzero. */
    \\[[__nodiscard__]] static inline chryso_abi_reject
    \\chryso_status_copy_verdict(uint64_t seq_before, uint64_t seq_after) {
    \\  if (seq_before == 0u || (seq_before & 1u) != 0u || seq_before != seq_after) {
    \\    return chryso_abi_reject_torn;
    \\  }
    \\  return chryso_abi_reject_ok;
    \\}
    \\
    \\
;

fn writeSystemValue(w: *Writer, comptime prefix: []const u8, comptime name: []const u8, value: anytype) Writer.Error!void {
    const T = @TypeOf(value);
    switch (@typeInfo(T)) {
        .int => |info| {
            try w.print("static constexpr {s} chryso_{s}_{s} = ", .{ scalarType(info.bits / 8), prefix, name });
            if (info.bits == 64 and (std.mem.indexOf(u8, name, "vaddr") != null or std.mem.indexOf(u8, name, "stride") != null))
                try w.print("UINT64_C(0x{x})", .{value})
            else
                try writeLiteral(w, value, info.bits / 8);
            try w.writeAll(";\n");
        },
        // Cacheability flags and strings (setvars, ELF names, sections) only shape the SDF.
        .bool, .pointer => {},
        .@"struct" => |info| {
            inline for (info.fields) |field| {
                const nested = if (name.len == 0) field.name else name ++ "_" ++ field.name;
                try writeSystemValue(w, prefix, nested, @field(value, field.name));
            }
        },
        .array => |info| {
            const Element = info.child;
            try w.print("static constexpr size_t chryso_{s}_{s}_count = {d}u;\n\n", .{ prefix, name, info.len });
            try w.print("typedef struct chryso_{s}_class {{\n", .{prefix});
            inline for (@typeInfo(Element).@"struct".fields) |field| {
                if (@typeInfo(field.type) == .int)
                    try w.print("  {s} {s};\n", .{ scalarType(@typeInfo(field.type).int.bits / 8), field.name });
            }
            try w.print("}} chryso_{s}_class;\n\n", .{prefix});
            try w.print("static const chryso_{s}_class chryso_{s}_{s}[{d}] = {{\n", .{ prefix, prefix, name, info.len });
            for (value) |row| {
                try w.writeAll("    {");
                var first = true;
                inline for (@typeInfo(Element).@"struct".fields) |field| {
                    if (@typeInfo(field.type) == .int) {
                        if (!first) try w.writeAll(", ");
                        first = false;
                        try w.print(".{s} = ", .{field.name});
                        try writeLiteral(w, @field(row, field.name), @typeInfo(field.type).int.bits / 8);
                    }
                }
                if (@hasField(Element, "name")) try w.print("}}, /* {s} */\n", .{row.name}) else try w.writeAll("},\n");
            }
            try w.writeAll("};\n\n");
        },
        else => @compileError("unsupported system ABI value " ++ @typeName(T)),
    }
}

fn writeSystem(w: *Writer) Writer.Error!void {
    try w.writeAll(
        \\/* Mapped regions reach each PD through its setvar_vaddr symbol, patched by the
        \\ * Microkit tool. The vaddr constants below exist to check those symbols and the
        \\ * SDF against, never as the address a PD dereferences. */
        \\
        \\
    );
    try w.writeAll("/* Control plane. */\n");
    try writeSystemValue(w, "control", "", system.values.control);
    try w.writeAll("\n/* Worker pool. */\n");
    try writeSystemValue(w, "pool", "", system.values.pool);
}

pub const RenderError = Writer.Error || error{ UnknownRecord, UnknownChecker };

fn writeHeader(w: *Writer, header: Header) RenderError!void {
    try writePreamble(w, header);
    switch (header.kind) {
        .common => try writeCommon(w),
        .system => try writeSystem(w),
        .records => {
            for (header.records) |name| {
                const record = checks.findRecord(model.description, name) orelse return error.UnknownRecord;
                try writeRecord(w, record);
            }
            if (header.status_copy) try w.writeAll(status_copy);
            for (header.checkers) |name| {
                const checker = checks.findChecker(&checks.checkers, name) orelse return error.UnknownChecker;
                try writeChecker(w, checker);
            }
        },
    }
    try w.print("#endif /* {s} */\n", .{header.guard});
}

/// Caller owns the returned bytes.
pub fn render(allocator: std.mem.Allocator, header: Header) (RenderError || std.mem.Allocator.Error)![]u8 {
    var out: Writer.Allocating = .init(allocator);
    defer out.deinit();
    try writeHeader(&out.writer, header);
    return out.toOwnedSlice();
}

/// Write every header to `<dir>/chrysopolis/`.
pub fn writeAll(allocator: std.mem.Allocator, dir: std.fs.Dir) !void {
    try dir.makePath("chrysopolis");
    var sub = try dir.openDir("chrysopolis", .{});
    defer sub.close();
    for (headers) |header| {
        const bytes = try render(allocator, header);
        defer allocator.free(bytes);
        try sub.writeFile(.{ .sub_path = header.name, .data = bytes });
    }
}

test "every record and checker lands in exactly one header" {
    for (model.description.records) |record| {
        var seen: usize = 0;
        for (headers) |header| {
            for (header.records) |name| {
                if (std.mem.eql(u8, name, record.name)) seen += 1;
            }
        }
        try std.testing.expectEqual(@as(usize, 1), seen);
    }
    for (checks.checkers) |checker| {
        var seen: usize = 0;
        for (headers) |header| {
            for (header.checkers) |name| {
                if (std.mem.eql(u8, name, checker.name)) seen += 1;
            }
        }
        try std.testing.expectEqual(@as(usize, 1), seen);
    }
}

test "rendering is deterministic and carries the pinned layout" {
    const allocator = std.testing.allocator;
    const expected = [_]struct { header: usize, snippets: []const []const u8 }{
        .{ .header = 0, .snippets = &.{
            "static constexpr uint64_t chryso_magic_status = UINT64_C(0x3141545359524843); /* \"CHRYSTA1\" */",
            "typedef enum chryso_root_child_wire_state : uint8_t {\n  chryso_root_child_wire_state_unset = 0u,",
            "typedef enum chryso_pp_opcode : uint16_t {\n  chryso_pp_opcode_unset = 0u,",
            "typedef enum chryso_completion_kind : uint32_t {\n  chryso_completion_kind_work = 0x8001u,",
            "static const chryso_slot_transition chryso_slot_transitions[17]",
        } },
        .{ .header = 1, .snippets = &.{
            "  _Atomic(uint64_t) seq;",
            "  _Atomic(uint32_t) active_bank;",
            "  _Atomic(uint32_t) bank_seq;",
            "  chryso_root_child_status children[62];",
            "static_assert(sizeof(chryso_root_status_page) == 16384);",
            "static_assert(offsetof(chryso_root_status_page, events) == 5048);",
            "static_assert(offsetof(chryso_spec_bank, bank_seq) == 20);",
            "chryso_check_spec_bank(const uint8_t *bytes, size_t len, size_t bank)",
            "chryso_status_copy_verdict(uint64_t seq_before, uint64_t seq_after)",
        } },
        .{ .header = 2, .snippets = &.{"  _Atomic(uint64_t) completion_ack;"} },
        .{ .header = 3, .snippets = &.{ "  _Atomic(uint64_t) status_seq;", "static_assert(offsetof(chryso_worker_status_header, status_seq) == 80);" } },
        .{ .header = 4, .snippets = &.{ "  _Atomic(uint64_t) published_seq;", "static_assert(sizeof(chryso_journal_page) == 4096);" } },
        .{ .header = 5, .snippets = &.{
            "static constexpr uint8_t chryso_control_pp_channel_root = 11u;",
            "static constexpr uint64_t chryso_control_status_root_vaddr = UINT64_C(0x40000000);",
            "static constexpr uint8_t chryso_pool_slots = 16u;",
            "static const chryso_pool_class chryso_pool_classes[2]",
        } },
    };
    for (expected) |case| {
        const first = try render(allocator, headers[case.header]);
        defer allocator.free(first);
        const second = try render(allocator, headers[case.header]);
        defer allocator.free(second);
        try std.testing.expectEqualStrings(first, second);
        for (case.snippets) |snippet| {
            if (std.mem.indexOf(u8, first, snippet) == null) {
                std.debug.print("{s} lacks:\n{s}\n", .{ headers[case.header].name, snippet });
                return error.MissingSnippet;
            }
        }
    }
}

test "every atomic field is rendered _Atomic at its declared width" {
    const allocator = std.testing.allocator;
    for (abi.atomic_fields) |atomic| {
        var found = false;
        for (headers) |header| {
            if (header.kind != .records) continue;
            const text = try render(allocator, header);
            defer allocator.free(text);
            const line = try std.fmt.allocPrint(allocator, "  _Atomic({s}) {s};", .{ scalarType(atomic.width), atomic.field });
            defer allocator.free(line);
            if (std.mem.indexOf(u8, text, line) != null) found = true;
        }
        try std.testing.expect(found);
    }
}
