//! Erlang projection of the orchestration ABI: `orchestrator_abi.hrl` and `chryso_abi_codec.erl`.
//! Checkers come from the same checks.zig tables as the C headers, so both languages share
//! layout, precedence and reason classes. Output is written into a build directory, never committed.
const std = @import("std");
const abi = @import("orchestrator_abi");
const model = @import("model");
const checks = @import("checks");
const naming = @import("naming");

const Writer = std.Io.Writer;
const snake = naming.snake;
const camel = naming.camel;
const upper = naming.upper;

pub const RenderError = Writer.Error || error{ UnknownRecord, UnknownChecker, UnknownField };

/// Nominal generation types: a spec generation and a slot generation must never be interchanged.
const Nominal = struct { record: []const u8, field: []const u8, type_name: []const u8 };
const nominals = [_]Nominal{
    .{ .record = "RootStatusHeader", .field = "applied_spec_generation", .type_name = "spec_generation" },
    .{ .record = "SpecBank", .field = "generation", .type_name = "spec_generation" },
    .{ .record = "RootChildStatus", .field = "slot_generation", .type_name = "slot_generation" },
    .{ .record = "WorkerIdentityHeader", .field = "generation", .type_name = "slot_generation" },
    .{ .record = "WorkerStatusHeader", .field = "generation", .type_name = "slot_generation" },
    .{ .record = "JournalHeader", .field = "generation", .type_name = "slot_generation" },
    .{ .record = "JournalEntry", .field = "generation", .type_name = "slot_generation" },
};

fn nominalFor(record: []const u8, field: []const u8) ?[]const u8 {
    for (nominals) |item| {
        if (std.mem.eql(u8, item.record, record) and std.mem.eql(u8, item.field, field)) return item.type_name;
    }
    return null;
}

fn isReserved(name: []const u8) bool {
    return std.mem.startsWith(u8, name, "reserved") or std.mem.startsWith(u8, name, "pad");
}

fn isMagic(field: model.Field) bool {
    return std.mem.eql(u8, field.name, "magic");
}

fn elementBits(field: model.Field) usize {
    return field.size / field.count * 8;
}

fn findRecord(name: []const u8) RenderError!model.Record {
    return checks.findRecord(model.description, name) orelse error.UnknownRecord;
}

fn fieldAt(record: model.Record, offset: usize) RenderError!model.Field {
    for (record.fields) |field| {
        if (field.offset == offset) return field;
    }
    return error.UnknownField;
}

fn magicBytes(value: u64) []const u8 {
    for (model.description.magics) |magic| {
        if (magic.value == value) return magic.bytes;
    }
    unreachable; // checks.validateChecker ties rule magics to declared magics
}

fn writeBanner(w: *Writer, summary: []const u8) Writer.Error!void {
    try w.print(
        \\%% Generated by tools/abi from interfaces/orchestrator_abi.zig. Do not edit and do not commit.
        \\%% {s}
        \\
    , .{summary});
}

// ---------------------------------------------------------------------------------------------
// orchestrator_abi.hrl

fn writeHeader(w: *Writer) RenderError!void {
    const d = model.description;
    try writeBanner(w, "Constants shared with the C contract in <chrysopolis/orchestrator_abi.h>.");
    try w.writeAll("-ifndef(CHRYSO_ORCHESTRATOR_ABI_HRL).\n-define(CHRYSO_ORCHESTRATOR_ABI_HRL, true).\n\n");
    try w.print("-define(CHRYSO_ABI_VERSION, {d}).\n", .{d.abi_version});
    try w.print("-define(CHRYSO_ABI_LAYOUT_DIGEST, 16#{x:0>8}).\n", .{model.layoutDigest(d)});
    try w.print("-define(CHRYSO_CHILD_COUNT, {d}).\n", .{d.constants.child_count});
    try w.print("-define(CHRYSO_EVENT_COUNT, {d}).\n", .{d.constants.event_count});
    try w.print("-define(CHRYSO_JOURNAL_CAPACITY, {d}).\n", .{d.constants.journal_capacity});
    try w.print("-define(CHRYSO_JOURNAL_PAYLOAD_SIZE, {d}).\n", .{d.constants.journal_payload_size});
    try w.print("-define(CHRYSO_ROOT_EVENT_NO_CHILD, {d}).\n", .{d.constants.root_event_no_child});
    try w.print("-define(CHRYSO_FAULT_MR0_VALID, {d}).\n", .{d.constants.fault_mr0_valid});
    try w.print("-define(CHRYSO_FAULT_MR1_VALID, {d}).\n", .{d.constants.fault_mr1_valid});
    try w.print("-define(CHRYSO_DOWN_INTERVAL_OPEN, {d}).\n\n", .{d.constants.down_interval_open});
    for (d.magics) |magic| {
        try w.print("-define(CHRYSO_MAGIC_{f}, <<\"{s}\">>).\n", .{ upper(magic.name), magic.bytes });
    }
    try w.writeByte('\n');
    for (d.records) |record| {
        try w.print("-define(CHRYSO_{f}_SIZE, {d}).\n", .{ upper(record.name), record.size });
        for (record.fields) |field| {
            try w.print("-define(CHRYSO_{f}_{f}_OFFSET, {d}).\n", .{ upper(record.name), upper(field.name), field.offset });
        }
    }
    try w.writeByte('\n');
    for (d.enums) |enumeration| {
        for (enumeration.values) |value| {
            try w.print("-define(CHRYSO_{f}_{f}, {d}).\n", .{ upper(enumeration.name), upper(value.name), value.value });
        }
    }
    try w.writeAll("\n-endif.\n");
}

// ---------------------------------------------------------------------------------------------
// Types

fn writeScalarType(w: *Writer, bits: usize) Writer.Error!void {
    try w.print("0..{d}", .{(@as(u128, 1) << @as(u7, @intCast(bits))) - 1});
}

fn writeFieldType(w: *Writer, record: model.Record, field: model.Field) Writer.Error!void {
    if (isMagic(field)) return w.writeAll("<<_:64>>");
    if (field.is_record) {
        if (field.count == 1) return w.print("{f}()", .{snake(field.element)});
        return w.print("[{f}()]", .{snake(field.element)});
    }
    if (field.count > 1 and elementBits(field) == 8) return w.writeAll("binary()");
    if (field.count > 1) {
        try w.writeByte('[');
        try writeScalarType(w, elementBits(field));
        return w.writeByte(']');
    }
    if (nominalFor(record.name, field.name)) |nominal| return w.print("{s}()", .{nominal});
    try writeScalarType(w, elementBits(field));
}

fn writeTypes(w: *Writer) RenderError!void {
    try w.writeAll(
        \\-doc "Why a snapshot was rejected; the same classes and precedence as the C checkers.".
        \\-type reject() :: size | magic | version | torn | checksum | reserved | unknown_kind | range.
        \\-doc "Generation of a published spec bank. Nominal, so it cannot be mixed with a slot generation.".
        \\-nominal spec_generation() :: 0..18446744073709551615.
        \\-doc "Generation of a pool slot's occupant, used to fence stale workers and journals.".
        \\-nominal slot_generation() :: 0..18446744073709551615.
        \\
    );
    for (model.description.records) |record| {
        try w.print("-doc \"The `{s}` wire record ({d} bytes) with reserved fields omitted.\".\n", .{ record.name, record.size });
        try w.print("-type {f}() :: #{{\n", .{snake(record.name)});
        var first = true;
        for (record.fields) |field| {
            if (isReserved(field.name)) continue;
            if (!first) try w.writeAll(",\n");
            first = false;
            try w.print("    {s} := ", .{field.name});
            try writeFieldType(w, record, field);
        }
        try w.writeAll("\n}.\n");
    }
    for (model.description.enums) |enumeration| {
        try w.print("-doc \"Tags of `{s}`.\".\n", .{enumeration.name});
        try w.print("-type {f}() :: ", .{snake(enumeration.name)});
        for (enumeration.values, 0..) |value, i| {
            if (i != 0) try w.writeAll(" | ");
            try w.writeAll(value.name);
        }
        try w.writeAll(".\n");
    }
    try w.writeAll(
        \\-doc "A spec page whose header passed, with each bank's own verdict.".
        \\-type checked_spec_page() :: #{header := spec_header(), banks := [{ok, spec_bank()} | {error, reject()}]}.
        \\
        \\-export_type([reject/0, spec_generation/0, slot_generation/0, checked_spec_page/0
    );
    for (model.description.records) |record| try w.print(", {f}/0", .{snake(record.name)});
    for (model.description.enums) |enumeration| try w.print(", {f}/0", .{snake(enumeration.name)});
    try w.writeAll("]).\n\n");
}

// ---------------------------------------------------------------------------------------------
// Checkers

/// Offset expression of a rule field: absolute for whole scope, `At + n` inside rows and windows.
const Offset = struct {
    base: ?[]const u8,
    value: usize,
    pub fn format(self: Offset, w: *Writer) Writer.Error!void {
        if (self.base) |base| {
            if (self.value == 0) return w.writeAll(base);
            return w.print("{s} + {d}", .{ base, self.value });
        }
        try w.print("{d}", .{self.value});
    }
};

fn writeLoad(w: *Writer, base: ?[]const u8, int: checks.Int) Writer.Error!void {
    try w.print("u(Bin, {f}, {d})", .{ Offset{ .base = base, .value = int.offset }, int.width * 8 });
}

fn writeZero(w: *Writer, base: ?[]const u8, offset: usize, len: usize) Writer.Error!void {
    // The literal is a constant term, so the comparison allocates nothing.
    try w.print("zero(Bin, {f}, <<0:{d}>>)", .{ Offset{ .base = base, .value = offset }, len * 8 });
}

/// A boolean Erlang expression that holds when the rule holds at this scope instance.
fn writeCondition(w: *Writer, check: checks.Check, base: ?[]const u8) RenderError!void {
    switch (check) {
        .magic => |value| try w.print("binary:part(Bin, {f}, 8) =:= <<\"{s}\">>", .{ Offset{ .base = base, .value = value.int.offset }, magicBytes(value.value) }),
        .version, .equal => |value| {
            try writeLoad(w, base, value.int);
            try w.print(" =:= {d}", .{value.value});
        },
        .at_most => |value| {
            try writeLoad(w, base, value.int);
            try w.print(" =< {d}", .{value.value});
        },
        .ring_dropped => |value| {
            try writeLoad(w, base, value.dropped);
            try w.writeAll(" =:= erlang:max(0, ");
            try writeLoad(w, base, value.head);
            try w.print(" - {d})", .{value.capacity});
        },
        .event_child => |value| {
            try w.writeAll("(case ");
            try writeLoad(w, base, value.kind);
            try w.writeAll(" of ");
            for (value.global) |kind| {
                try w.print("{d} -> ", .{kind});
                try writeLoad(w, base, value.child);
                try w.print(" =:= {d}; ", .{value.sentinel});
            }
            try w.writeAll("_ -> (");
            try writeLoad(w, base, value.child);
            try w.print(" < {d} andalso u(Bin, {d} + ", .{ value.targets.count, value.targets.base });
            try writeLoad(w, base, value.child);
            try w.print(" * {d} + {d}, 8) =/= 0) end)", .{ value.targets.stride, value.target_state.offset });
        },
        .only_for_kind => |value| {
            try w.writeByte('(');
            try writeLoad(w, base, value.int);
            try w.writeAll(" =:= 0 orelse ");
            try writeLoad(w, base, value.kind);
            try w.print(" =:= {d})", .{value.value});
        },
        .implies => |value| {
            try w.writeByte('(');
            try writeLoad(w, base, value.int);
            try w.print(" band {d} =:= 0 orelse ", .{value.when});
            try writeLoad(w, base, value.int);
            try w.print(" band {d} =:= {d})", .{ value.requires, value.requires });
        },
        .zero_when_unset => |value| {
            try w.writeByte('(');
            try writeLoad(w, base, value.int);
            try w.writeAll(" =/= 0 orelse ");
            try writeZero(w, base, value.span.offset, value.span.len);
            try w.writeByte(')');
        },
        .kind_member => |value| {
            try w.writeByte('(');
            try writeLoad(w, base, value.kind);
            try w.print(" =/= {d} orelse ", .{value.value});
            try writeCondition(w, .{ .member = value.member }, base);
            try w.writeByte(')');
        },
        .seqlock => |value| {
            try w.writeAll("published(");
            try writeLoad(w, base, value);
            try w.writeAll(")");
        },
        .nonzero => |value| {
            try writeLoad(w, base, value);
            try w.writeAll(" =/= 0");
        },
        .zero => |value| try writeZero(w, base, value.offset, value.len),
        .member => |value| {
            if (value.reject_zero) {
                try w.print("nonzero_member(fun is_{f}/1, ", .{snake(value.enumeration)});
            } else {
                try w.print("is_{f}(", .{snake(value.enumeration)});
            }
            try writeLoad(w, base, value.int);
            try w.writeAll(")");
        },
        .crc32 => |value| {
            try w.writeAll("erlang:crc32([");
            var cursor = value.span.offset;
            var first = true;
            const stored = [_]checks.Span{.{ .offset = value.crc.offset, .len = value.crc.width }};
            for ([_][]const checks.Span{ &stored, value.zeroed }) |group| {
                for (group) |zeroed| {
                    if (zeroed.offset > cursor) {
                        if (!first) try w.writeAll(", ");
                        try w.print("binary:part(Bin, {f}, {d})", .{ Offset{ .base = base, .value = cursor }, zeroed.offset - cursor });
                        first = false;
                    }
                    if (!first) try w.writeAll(", ");
                    try w.print("<<0:{d}>>", .{zeroed.len * 8});
                    first = false;
                    cursor = zeroed.offset + zeroed.len;
                }
            }
            const end = value.span.offset + value.span.len;
            if (end > cursor) try w.print(", binary:part(Bin, {f}, {d})", .{ Offset{ .base = base, .value = cursor }, end - cursor });
            try w.writeAll("]) =:= ");
            try writeLoad(w, base, value.crc);
        },
        .entry_identity => |value| {
            try writeLoad(w, base, value.generation);
            try w.print(" =:= u(Bin, {d}, 64) andalso ", .{value.header_generation});
            try writeLoad(w, base, value.sequence);
            try w.writeAll(" =:= Seq");
        },
        .payload_tail => |value| try w.print("payload_tail(Bin, {f}, {d}, {f}, {d})", .{
            Offset{ .base = base, .value = value.length.offset },  value.length.width * 8,
            Offset{ .base = base, .value = value.payload.offset }, value.payload.len,
        }),
    }
}

fn usesSequence(group: []const checks.Rule) bool {
    for (group) |rule| {
        if (rule.check == .entry_identity) return true;
    }
    return false;
}

fn writeConditions(w: *Writer, group: []const checks.Rule, base: ?[]const u8) RenderError!void {
    for (group, 0..) |rule, i| {
        if (i != 0) try w.writeAll(" andalso\n            ");
        try writeCondition(w, rule.check, base);
    }
}

/// One `ok ?= expect(..., Class)` line per group of rules sharing class and scope.
fn writeGroup(w: *Writer, group: []const checks.Rule) RenderError!void {
    const class = @tagName(group[0].class);
    try w.writeAll("        ok ?= expect(");
    switch (group[0].scope) {
        .whole => try writeConditions(w, group, null),
        .selected => try writeConditions(w, group, "At"),
        .rows => |rows| {
            try w.writeAll("all_rows(fun(At) ->\n            ");
            try writeConditions(w, group, "At");
            try w.print("\n        end, {d}, {d}, {d})", .{ rows.base, rows.stride, rows.count });
        },
        .window => |window| {
            try w.print("all_live(fun(At, {s}) ->\n            ", .{if (usesSequence(group)) "Seq" else "_Seq"});
            try writeConditions(w, group, "At");
            try w.print("\n        end, u(Bin, {d}, 64), {d}, {d}, {d})", .{ window.head_offset, window.base, window.stride, window.capacity });
        },
    }
    try w.print(", {s})", .{class});
}

fn writeChecker(w: *Writer, checker: checks.Checker) RenderError!void {
    const name = checker.name;
    if (checker.selector) |selector| {
        try w.print(
            \\-doc """
            \\Checks bank `Bank` of a `{s}` snapshot. An invalid index is `range`; the other bank
            \\is not examined, so a torn inactive bank never hides a committed active one.
            \\""".
            \\-doc #{{group => ~"Checkers"}}.
            \\-spec check_{s}(term(), term()) -> ok | {{error, reject()}}.
            \\check_{s}(Bin, Bank) when is_binary(Bin), byte_size(Bin) =:= {d}, is_integer(Bank), Bank >= 0, Bank < {d} ->
            \\    At = {d} + Bank * {d},
            \\
        , .{ checker.record, name, name, checker.size, selector.count, selector.base, selector.stride });
    } else {
        try w.print(
            \\-doc """
            \\Checks a `{s}` snapshot of exactly {d} bytes. Returns the highest-precedence
            \\violation, or `ok`. Total over any term.
            \\""".
            \\-doc #{{group => ~"Checkers"}}.
            \\-spec check_{s}(term()) -> ok | {{error, reject()}}.
            \\check_{s}(Bin) when is_binary(Bin), byte_size(Bin) =:= {d} ->
            \\
        , .{ checker.record, checker.size, name, name, checker.size });
    }
    try w.writeAll("    maybe\n");
    var start: usize = 0;
    var first = true;
    while (start < checker.rules.len) {
        var end = start + 1;
        while (end < checker.rules.len and checker.rules[end].class == checker.rules[start].class and
            std.meta.eql(checker.rules[end].scope, checker.rules[start].scope)) end += 1;
        if (!first) try w.writeAll(",\n");
        first = false;
        try writeGroup(w, checker.rules[start..end]);
        start = end;
    }
    try w.writeAll("\n    end;\n");
    if (checker.selector != null) {
        try w.print(
            \\check_{s}(Bin, _Bank) when is_binary(Bin), byte_size(Bin) =:= {d} ->
            \\    {{error, range}};
            \\check_{s}(_Bin, _Bank) ->
            \\    {{error, size}}.
            \\
            \\
        , .{ name, checker.size, name });
    } else {
        try w.print("check_{s}(_Bin) ->\n    {{error, size}}.\n\n", .{name});
    }
}

// ---------------------------------------------------------------------------------------------
// Record codecs

fn writeFromBinary(w: *Writer, record: model.Record) Writer.Error!void {
    const name = snake(record.name);
    try w.print("-doc \"Unchecked field decode of a {d}-byte `{s}`; run the checker first for untrusted input.\".\n", .{ record.size, record.name });
    try w.writeAll("-doc #{group => ~\"Records\"}.\n");
    try w.print("-spec {f}_from_binary(binary()) -> {f}().\n{f}_from_binary(<<", .{ name, name, name });
    for (record.fields, 0..) |field, i| {
        if (i != 0) try w.writeAll(", ");
        if (isReserved(field.name)) {
            try w.print("_:{d}/binary", .{field.size});
        } else if (isMagic(field) or field.is_record or field.count > 1) {
            try w.print("{f}:{d}/binary", .{ camel(field.name), field.size });
        } else {
            try w.print("{f}:{d}/little", .{ camel(field.name), elementBits(field) });
        }
    }
    // One multi-field pattern binds every field, so the compiler keeps a single match context.
    try w.writeAll(">>) ->\n    #{");
    var first = true;
    for (record.fields) |field| {
        if (isReserved(field.name)) continue;
        if (!first) try w.writeAll(",\n      ");
        first = false;
        try w.print("{s} => ", .{field.name});
        const v = camel(field.name);
        if (isMagic(field)) {
            try w.print("{f}", .{v});
        } else if (field.is_record and field.count == 1) {
            try w.print("{f}_from_binary({f})", .{ snake(field.element), v });
        } else if (field.is_record) {
            try w.print("[{f}_from_binary(E) || <<E:{d}/binary>> <= {f}]", .{ snake(field.element), field.size / field.count, v });
        } else if (field.count > 1 and elementBits(field) == 8) {
            // A copy, so a small field never pins the whole page binary.
            try w.print("binary:copy({f})", .{v});
        } else if (field.count > 1) {
            try w.print("[E || <<E:{d}/little>> <= {f}]", .{ elementBits(field), v });
        } else {
            try w.print("{f}", .{v});
        }
    }
    try w.writeAll("\n    }.\n\n");
}

fn writeToBinary(w: *Writer, record: model.Record) Writer.Error!void {
    const name = snake(record.name);
    try w.print("-doc \"Encodes a `{s}` with zeroed reserved bytes. Raises `badarg` on an out-of-range field.\".\n", .{record.name});
    try w.writeAll("-doc #{group => ~\"Records\"}.\n");
    try w.print("-spec {f}_to_binary({f}()) -> binary().\n{f}_to_binary(#{{", .{ name, name, name });
    var first = true;
    for (record.fields) |field| {
        if (isReserved(field.name)) continue;
        if (!first) try w.writeAll(", ");
        first = false;
        try w.print("{s} := {f}", .{ field.name, camel(field.name) });
    }
    try w.writeAll("}) ->\n    <<");
    for (record.fields, 0..) |field, i| {
        if (i != 0) try w.writeAll(",\n      ");
        const v = camel(field.name);
        if (isReserved(field.name)) {
            try w.print("0:{d}", .{field.size * 8});
        } else if (isMagic(field)) {
            try w.print("(bytes({f}, 8))/binary", .{v});
        } else if (field.is_record and field.count == 1) {
            try w.print("({f}_to_binary({f}))/binary", .{ snake(field.element), v });
        } else if (field.is_record) {
            try w.print("(rows(fun {f}_to_binary/1, {f}, {d}))/binary", .{ snake(field.element), v, field.count });
        } else if (field.count > 1 and elementBits(field) == 8) {
            try w.print("(bytes({f}, {d}))/binary", .{ v, field.count });
        } else if (field.count > 1) {
            try w.print("(uints({f}, {d}, {d}))/binary", .{ v, field.count, elementBits(field) });
        } else {
            try w.print("(uint({f}, {d})):{d}/little", .{ v, elementBits(field), elementBits(field) });
        }
    }
    try w.writeAll(">>.\n\n");
}

/// `seal_<record>/1` for each CRC rule: fills in the CRC, reading the zeroed spans as zero.
fn writeSeal(w: *Writer, checker: checks.Checker) RenderError!void {
    const page = try findRecord(checker.record);
    for (checker.rules) |rule| {
        if (rule.check != .crc32) continue;
        const crc = rule.check.crc32;
        const rows = rule.scope.selected;
        const bank = try findRecord((try fieldAt(page, rows.base)).element);
        const name = snake(bank.name);
        // Pieces between the stored CRC and the zeroed spans, in offset order.
        const Piece = struct { offset: usize, len: usize, kind: enum { keep, crc, zeroed } };
        var pieces: [8]Piece = undefined;
        var count: usize = 0;
        var cursor: usize = crc.span.offset;
        const stored = [_]checks.Span{.{ .offset = crc.crc.offset, .len = crc.crc.width }};
        for ([_][]const checks.Span{ &stored, crc.zeroed }, 0..) |group, g| {
            for (group) |span| {
                if (span.offset > cursor) {
                    pieces[count] = .{ .offset = cursor, .len = span.offset - cursor, .kind = .keep };
                    count += 1;
                }
                pieces[count] = .{ .offset = span.offset, .len = span.len, .kind = if (g == 0) .crc else .zeroed };
                count += 1;
                cursor = span.offset + span.len;
            }
        }
        const end = crc.span.offset + crc.span.len;
        if (end > cursor) {
            pieces[count] = .{ .offset = cursor, .len = end - cursor, .kind = .keep };
            count += 1;
        }
        try w.print("-doc \"Stores the CRC-32 of a `{s}`, computed with the CRC and zeroed fields read as zero.\".\n", .{bank.name});
        try w.writeAll("-doc #{group => ~\"Records\"}.\n");
        try w.print("-spec seal_{f}(binary()) -> binary().\nseal_{f}(<<", .{ name, name });
        for (pieces[0..count], 0..) |piece, i| {
            if (i != 0) try w.writeAll(", ");
            switch (piece.kind) {
                .crc => try w.print("_:{d}", .{piece.len * 8}),
                .keep, .zeroed => try w.print("P{d}:{d}/binary", .{ i, piece.len }),
            }
        }
        try w.writeAll(">>) ->\n    Crc = erlang:crc32([");
        for (pieces[0..count], 0..) |piece, i| {
            if (i != 0) try w.writeAll(", ");
            switch (piece.kind) {
                .keep => try w.print("P{d}", .{i}),
                .crc, .zeroed => try w.print("<<0:{d}>>", .{piece.len * 8}),
            }
        }
        try w.writeAll("]),\n    <<");
        for (pieces[0..count], 0..) |piece, i| {
            if (i != 0) try w.writeAll(", ");
            switch (piece.kind) {
                .crc => try w.print("Crc:{d}/little", .{piece.len * 8}),
                .keep, .zeroed => try w.print("P{d}/binary", .{i}),
            }
        }
        try w.writeAll(">>.\n\n");
    }
}

// ---------------------------------------------------------------------------------------------
// Validated decoders

fn hasSelectorSibling(checker: checks.Checker) bool {
    for (checks.checkers) |other| {
        if (other.selector != null and std.mem.eql(u8, other.record, checker.record)) return true;
    }
    return false;
}

fn writeDecoder(w: *Writer, checker: checks.Checker) RenderError!void {
    if (checker.selector != null) return; // decoded through its page decoder
    const record = try findRecord(checker.record);
    const record_name = snake(record.name);
    if (hasSelectorSibling(checker)) {
        // Bank validity is per bank: a torn inactive bank must not hide a valid active one.
        var selector: checks.Checker = undefined;
        for (checks.checkers) |other| {
            if (other.selector != null and std.mem.eql(u8, other.record, checker.record)) selector = other;
        }
        const rows = selector.selector.?;
        const bank = try findRecord((try fieldAt(record, rows.base)).element);
        const header = record.fields[0];
        try w.print(
            \\-doc "Checks and decodes a spec page: the header must pass; each bank carries its own verdict.".
            \\-doc #{{group => ~"Decoders"}}.
            \\-spec decode_{f}(binary()) -> {{ok, checked_{f}()}} | {{error, reject()}}.
            \\decode_{f}(Bin) ->
            \\    maybe
            \\        ok ?= check_{s}(Bin),
            \\        {{ok, #{{{s} => {f}_from_binary(binary:part(Bin, {d}, {d})),
            \\               banks => [case check_{s}(Bin, I) of
            \\                             ok -> {{ok, {f}_from_binary(binary:part(Bin, {d} + I * {d}, {d}))}};
            \\                             Error -> Error
            \\                         end || I <- lists:seq(0, {d})]}}}}
            \\    end.
            \\
            \\
        , .{
            record_name,           record_name,   record_name, checker.name,   header.name,
            snake(header.element), header.offset, header.size, selector.name,  snake(bank.name),
            rows.base,             rows.stride,   rows.stride, rows.count - 1,
        });
        return;
    }
    try w.print(
        \\-doc "Checks and decodes a `{s}` snapshot. Published windows hold only live rows, oldest first.".
        \\-doc #{{group => ~"Decoders"}}.
        \\-spec decode_{s}(binary()) -> {{ok, {f}()}} | {{error, reject()}}.
        \\decode_{s}(Bin) ->
        \\    maybe
        \\        ok ?= check_{s}(Bin),
        \\        Page = {f}_from_binary(Bin),
        \\
    , .{ checker.name, checker.name, record_name, checker.name, checker.name, record_name });
    // A published window returns only its live rows, oldest first.
    var window: ?checks.Window = null;
    var tail: ?checks.PayloadTail = null;
    for (checker.rules) |rule| {
        if (rule.scope == .window) window = rule.scope.window;
        if (rule.check == .payload_tail) tail = rule.check.payload_tail;
    }
    if (window) |live| {
        const field = try fieldAt(record, live.base);
        try w.print("        Live = live(maps:get({s}, Page), u(Bin, {d}, 64), {d}),\n", .{ field.name, live.head_offset, live.capacity });
        if (tail) |payload| {
            const entry = try findRecord(field.element);
            const length = try fieldAt(entry, payload.length.offset);
            const bytes = try fieldAt(entry, payload.payload.offset);
            try w.print(
                \\        Trimmed = [E#{{{s} := binary:part(maps:get({s}, E), 0, maps:get({s}, E))}} || E <- Live],
                \\        {{ok, Page#{{{s} := Trimmed}}}}
                \\
            , .{ bytes.name, bytes.name, length.name, field.name });
        } else {
            try w.print("        {{ok, Page#{{{s} := Live}}}}\n", .{field.name});
        }
    } else {
        try w.writeAll("        {ok, Page}\n");
    }
    try w.writeAll("    end.\n\n");
}

// ---------------------------------------------------------------------------------------------
// Enums

fn writeEnum(w: *Writer, enumeration: model.Enum) Writer.Error!void {
    const name = snake(enumeration.name);
    try w.print("-doc \"The `{s}` tag for a wire value, or `error` for an undeclared one.\".\n", .{enumeration.name});
    try w.writeAll("-doc #{group => ~\"Enums\"}.\n");
    try w.print("-spec {f}_to_atom(non_neg_integer()) -> {{ok, {f}()}} | error.\n", .{ name, name });
    for (enumeration.values) |value| try w.print("{f}_to_atom({d}) -> {{ok, {s}}};\n", .{ name, value.value, value.name });
    try w.print("{f}_to_atom(_) -> error.\n\n", .{name});
    try w.print("-doc \"The wire value of a `{s}` tag.\".\n", .{enumeration.name});
    try w.writeAll("-doc #{group => ~\"Enums\"}.\n");
    try w.print("-spec {f}_value({f}()) -> non_neg_integer().\n", .{ name, name });
    for (enumeration.values, 0..) |value, i| {
        try w.print("{f}_value({s}) -> {d}{s}\n", .{ name, value.name, value.value, if (i + 1 == enumeration.values.len) "." else ";" });
    }
    try w.writeByte('\n');
    if (!enumeration.wire) return;
    for (enumeration.values) |value| try w.print("is_{f}({d}) -> true;\n", .{ name, value.value });
    try w.print("is_{f}(_) -> false.\n\n", .{name});
}

// ---------------------------------------------------------------------------------------------
// Module

const helpers =
    \\%% Little-endian unsigned field of Bits bits at byte Offset.
    \\u(Bin, Offset, Bits) ->
    \\    <<_:Offset/binary, Value:Bits/little, _/binary>> = Bin,
    \\    Value.
    \\
    \\zero(Bin, Offset, Zeros) ->
    \\    binary:part(Bin, Offset, byte_size(Zeros)) =:= Zeros.
    \\
    \\published(Seq) ->
    \\    Seq =/= 0 andalso Seq band 1 =:= 0.
    \\
    \\%% A declared zero tag that the rule forbids (`unset` is never published there).
    \\nonzero_member(Member, Value) ->
    \\    Value =/= 0 andalso Member(Value).
    \\
    \\expect(true, _Class) -> ok;
    \\expect(false, Class) -> {error, Class}.
    \\
    \\all_rows(Check, Base, Stride, Count) ->
    \\    lists:all(fun(Row) -> Check(Base + Row * Stride) end, lists:seq(0, Count - 1)).
    \\
    \\%% Published rows only: indexes [Head - min(Head, Cap), Head) in slot Index rem Cap,
    \\%% where Index + 1 is the journal sequence.
    \\all_live(Check, Head, Base, Stride, Cap) ->
    \\    Live = min(Head, Cap),
    \\    lists:all(
    \\        fun(Index) -> Check(Base + (Index rem Cap) * Stride, Index + 1) end,
    \\        lists:seq(Head - Live, Head - 1)
    \\    ).
    \\
    \\live(Rows, Head, Cap) ->
    \\    Slots = list_to_tuple(Rows),
    \\    [element(Index rem Cap + 1, Slots) || Index <- lists:seq(Head - min(Head, Cap), Head - 1)].
    \\
    \\payload_tail(Bin, LengthOffset, LengthBits, PayloadOffset, PayloadSize) ->
    \\    Kept = min(u(Bin, LengthOffset, LengthBits), PayloadSize),
    \\    binary:part(Bin, PayloadOffset + Kept, PayloadSize - Kept) =:= <<0:((PayloadSize - Kept) * 8)>>.
    \\
    \\uint(Value, Bits) when is_integer(Value), Value >= 0, Value < 1 bsl Bits -> Value;
    \\uint(_, _) -> error(badarg).
    \\
    \\bytes(Value, Size) when is_binary(Value), byte_size(Value) =:= Size -> Value;
    \\bytes(_, _) -> error(badarg).
    \\
    \\uints(Values, Count, Bits) when is_list(Values), length(Values) =:= Count ->
    \\    <<<<(uint(V, Bits)):Bits/little>> || V <- Values>>;
    \\uints(_, _, _) -> error(badarg).
    \\
    \\rows(Encode, Values, Count) when is_list(Values), length(Values) =:= Count ->
    \\    <<<<(Encode(V))/binary>> || V <- Values>>;
    \\rows(_, _, _) -> error(badarg).
    \\
;

fn writeExports(w: *Writer) RenderError!void {
    try w.writeAll("-export([layout_digest/0, abi_version/0");
    for (checks.checkers) |checker| {
        try w.print(", check_{s}/{d}", .{ checker.name, @as(u8, if (checker.selector != null) 2 else 1) });
        if (checker.selector != null) continue;
        if (hasSelectorSibling(checker)) {
            try w.print(", decode_{f}/1", .{snake(checker.record)});
        } else {
            try w.print(", decode_{s}/1", .{checker.name});
        }
    }
    for (checks.checkers) |checker| {
        for (checker.rules) |rule| {
            if (rule.check == .crc32) try w.print(", seal_{f}/1", .{snake((try fieldAt(try findRecord(checker.record), rule.scope.selected.base)).element)});
        }
    }
    for (model.description.records) |record| try w.print(", {f}_from_binary/1, {f}_to_binary/1", .{ snake(record.name), snake(record.name) });
    for (model.description.enums) |enumeration| try w.print(", {f}_to_atom/1, {f}_value/1", .{ snake(enumeration.name), snake(enumeration.name) });
    try w.writeAll("]).\n\n");
}

fn writeCodec(w: *Writer) RenderError!void {
    try writeBanner(w, "Checkers, decoders and encoders for the orchestration wire records.");
    try w.writeAll(
        \\-module(chryso_abi_codec).
        \\-moduledoc """
        \\Codec for the orchestration wire records shared with Root and the workers.
        \\
        \\Every `check_*` function is total over any term and returns the same rejection
        \\classes, in the same precedence, as the generated C checkers in
        \\`<chrysopolis/*.h>`: `size`, `magic`, `version`, `torn`, `checksum`, `reserved`,
        \\`unknown_kind`, `range`.
        \\
        \\Decoders take a snapshot that the C side already copied under its seqlock. They
        \\cannot observe shared memory changing, so a torn copy is the caller's to retry.
        \\""".
        \\
        \\-include("orchestrator_abi.hrl").
        \\
        \\
    );
    try writeExports(w);
    try writeTypes(w);
    try w.writeAll(
        \\-doc "CRC-32 of the whole wire model; peers must agree on it before exchanging records.".
        \\-spec layout_digest() -> non_neg_integer().
        \\layout_digest() -> ?CHRYSO_ABI_LAYOUT_DIGEST.
        \\
        \\-doc "Wire ABI version carried in every record header.".
        \\-spec abi_version() -> non_neg_integer().
        \\abi_version() -> ?CHRYSO_ABI_VERSION.
        \\
        \\
    );
    for (checks.checkers) |checker| try writeChecker(w, checker);
    for (checks.checkers) |checker| try writeDecoder(w, checker);
    for (checks.checkers) |checker| try writeSeal(w, checker);
    for (model.description.records) |record| {
        try writeFromBinary(w, record);
        try writeToBinary(w, record);
    }
    for (model.description.enums) |enumeration| try writeEnum(w, enumeration);
    try w.writeAll(helpers);
}

pub const File = struct { path: []const u8, kind: enum { header, codec } };
pub const files = [_]File{
    .{ .path = "include/orchestrator_abi.hrl", .kind = .header },
    .{ .path = "src/chryso_abi_codec.erl", .kind = .codec },
};

/// Caller owns the returned bytes.
pub fn render(allocator: std.mem.Allocator, file: File) (RenderError || std.mem.Allocator.Error)![]u8 {
    var out: Writer.Allocating = .init(allocator);
    defer out.deinit();
    switch (file.kind) {
        .header => try writeHeader(&out.writer),
        .codec => try writeCodec(&out.writer),
    }
    return out.toOwnedSlice();
}

/// Writes `include/` and `src/` under `dir`.
pub fn writeAll(allocator: std.mem.Allocator, dir: std.fs.Dir) !void {
    for (files) |file| {
        const bytes = try render(allocator, file);
        defer allocator.free(bytes);
        if (std.fs.path.dirname(file.path)) |parent| try dir.makePath(parent);
        try dir.writeFile(.{ .sub_path = file.path, .data = bytes });
    }
}

test "rendering is deterministic and carries the shared contract" {
    const allocator = std.testing.allocator;
    const Case = struct { file: File, snippets: []const []const u8 };
    const digest = try std.fmt.allocPrint(allocator, "-define(CHRYSO_ABI_LAYOUT_DIGEST, 16#{x:0>8}).", .{model.layoutDigest(model.description)});
    defer allocator.free(digest);
    const cases = [_]Case{
        .{ .file = files[0], .snippets = &.{
            digest,
            "-define(CHRYSO_MAGIC_STATUS, <<\"CHRYSTA1\">>).",
            "-define(CHRYSO_ROOT_STATUS_PAGE_EVENTS_OFFSET, 5048).",
            "-define(CHRYSO_PP_OPCODE_HELLO, 1).",
        } },
        .{ .file = files[1], .snippets = &.{
            "check_spec_bank(Bin, Bank) when is_binary(Bin), byte_size(Bin) =:= 4096, is_integer(Bank), Bank >= 0, Bank < 2 ->",
            "zero(Bin, 9144, <<0:57920>>)",
            "binary:part(Bin, 0, 8) =:= <<\"CHRYSTA1\">>",
            "-nominal slot_generation() ::",
            "decode_spec_page(Bin) ->",
            "seal_spec_bank(<<",
        } },
    };
    for (cases) |case| {
        const first = try render(allocator, case.file);
        defer allocator.free(first);
        const second = try render(allocator, case.file);
        defer allocator.free(second);
        try std.testing.expectEqualStrings(first, second);
        for (case.snippets) |snippet| {
            if (std.mem.indexOf(u8, first, snippet) == null) {
                std.debug.print("{s} lacks:\n{s}\n", .{ case.file.path, snippet });
                return error.MissingSnippet;
            }
        }
    }
}

test "every checker and record has its codec functions" {
    const allocator = std.testing.allocator;
    const codec = try render(allocator, files[1]);
    defer allocator.free(codec);
    for (checks.checkers) |checker| {
        const needle = try std.fmt.allocPrint(allocator, "\ncheck_{s}(", .{checker.name});
        defer allocator.free(needle);
        try std.testing.expect(std.mem.indexOf(u8, codec, needle) != null);
    }
    for (model.description.records) |record| {
        const needle = try std.fmt.allocPrint(allocator, "\n{f}_to_binary(#{{", .{snake(record.name)});
        defer allocator.free(needle);
        try std.testing.expect(std.mem.indexOf(u8, codec, needle) != null);
    }
}
