name: "[Nix] Update flake.lock"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Update flake.lock
        run: nix flake update
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          add-paths: flake.lock
          branch: automation/update-flake-lock
          commit-message: "[Nix] Update flake.lock"
          title: "[Nix] Update flake.lock"
          labels: |
            dependencies
            automation
